# Generated by Django 5.0 on 2023-12-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjects",
            old_name="name",
            new_name="username",
        ),
    ]
