# Generated by Django 5.0 on 2023-12-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_subjects_exam_subjects_year_alter_subjects_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjects",
            old_name="username",
            new_name="subject",
        ),
    ]
