# Generated by Django 5.0 on 2023-12-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_username_subjects_subject"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subjects",
            new_name="Subject",
        ),
    ]
