# Generated by Django 5.0 on 2023-12-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_rename_subjects_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
