# Generated by Django 5.0 on 2023-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_explicamisto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
